#!/bin/bash
####################################################################
# Script     : setup
# Authors    : Jon Oakley and Nathan Tusing
# Date       : 02/12/2019
# Description: Setup script that will setup and install and the 
#   necessary files on an Ubuntu machine.  These files are required
#   for the proxy to run.  Ubuntu 18.04 is required.  Also modifies
#   iptables so that RST packets are not sents when a connection is
#   started with a closed port.  This will not affect any existing
#   programs, but it is not the default behavior.  This assumes that
#   no existing firewalls are in place.   These rules will clobber
#   existing iptable rules.
####################################################################
SSHPORT=9002
TORDATADIR='/tmp/tor'
sudo yum update
#sudo yum install -y python3 python2.7 scapy python-crypto tor vim python-pip python-psutil scipy

#sudo pip3 install quarry
#sudo pip3 install twisted
sudo iptables --flush
sudo iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP
sudo iptables -L

# Installation
sudo cp bootstrap/bootstrap.py /usr/local/bin/
sudo cp configs/tsocks.conf /etc/tsocks.conf
echo "Port $SSHPORT" | sudo tee --append /etc/ssh/sshd_config > /dev/null
semanage port -a -t ssh_port_t -p tcp $SSHPORT
sudo service ssh restart
sudo cp configs/torrc /etc/tor/torrc
sudo mkdir -p $TORDATADIR
sudo chown -R `whoami` $TORDATADIR
sudo chmod u+rwx -R $TORDATADIR

echo "The following non-standard ssh port was opened"
echo "ssh -p $SSHPORT user@host"
echo ""
echo "Copy the ntp-proxy folder to wherever you would like to install it."
echo "Keep in mind the copy-certs.py file must be run from the that folder"
echo "Setup Complete"
