$static_ip = "192.168.2.177" #Change this to be an IP on your LAN such as 192.168.0.199/24 if your computer is on the same subnet 

$setup = <<SCRIPT
    cd /home/vagrant/minecruft/Minecraft_Server
    sudo ./setup_bridge.sh
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "PTDemo"

    config.vm.provider "virtualbox" do |a|
        a.memory = "2048"
        a.name = "Bridge_Node"
    end

    config.vm.network "public_network", ip: $static_ip 
    config.vm.synced_folder "..", "/home/vagrant/minecruft"

    config.vm.provision "shell", inline: $setup
    config.ssh.forward_agent = true
end
  
